package controllers

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"github.com/beego/beego/v2/core/logs"
	"github.com/cdle/xdd/models"
	"strings"
)

type WxController struct {
	BaseController
}

func (c *WxController) HandleMessage() {
	data := c.Ctx.Input.RequestBody

	type AutoGenerated struct {
		SdkVer  int    `json:"sdkVer"`
		Event   string `json:"Event"`
		Content struct {
			RobotWxid     string `json:"robot_wxid"`
			Type          int    `json:"type"`
			FromGroup     string `json:"from_group"`
			FromGroupName string `json:"from_group_name"`
			FromWxid      string `json:"from_wxid"`
			FromName      string `json:"from_name"`
			Msg           string `json:"msg"`
			Clientid      int    `json:"clientid"`
			RobotType     int    `json:"robot_type"`
		} `json:"content"`
	}

	ag := &AutoGenerated{}
	err := json.Unmarshal(data, ag)
	logs.Info(err)
	logs.Info("接收到信息" + ag.Content.Msg)
	if ag.Content.Type == 2000 {

	}
	switch ag.Content.Type {
	case 2000:

	}
	models.ListenWXTempPrivateMessage(ag.Content.FromWxid, ag.Content.Msg)

}

//func AgreeFriendVerify(uid string, msg string) {
//	type AutoGenerated1 struct {
//		API       string `json:"api"`        // API名
//		RobotWxid string `json:"robot_wxid"` // 机器人ID
//		Token     string `json:"token"`      // 验证密钥
//		Type      int64  `json:"type"`       // 收到好友验证消息中（json）的type属性
//		V1        string `json:"v1"`         // 收到好友验证消息中（json）的v1属性
//		V2        string `json:"v2"`         // 收到好友验证消息中（json）的v2属性
//
//	}
//
//	req := httplib.Post(models.Config.Wx.Url)
//	aggre := &AutoGenerated1{
//		Token:     "1",
//		API:       "AgreeFriendVerify",
//		RobotWxid: models.Config.Wx.Robotid,
//		ToWxid:    uid,
//		Msg:       msg,
//	}
//	random := browser.Random()
//	req.Header("User-Agent", random)
//	marshal, _ := json.Marshal(reply)
//	logs.Info(string(marshal))
//	req.Body(string(marshal))
//	s, _ := req.String()
//	logs.Info(s)
//}

func u2s(form string) (to string, err error) {
	bs, err := hex.DecodeString(strings.Replace(form, `\u`, ``, -1))
	if err != nil {
		return
	}
	for i, bl, br, r := 0, len(bs), bytes.NewReader(bs), uint16(0); i < bl; i += 2 {
		binary.Read(br, binary.BigEndian, &r)
		to += string(r)
	}
	return
}
