package controllers

import (
	"encoding/json"
	"github.com/beego/beego/v2/core/logs"
)

type WxController struct {
	BaseController
}

func (c *WxController) HandleMessage() {
	data := c.Ctx.Input.RequestBody
	type AutoGenerated struct {
		SdkVer  int    `json:"sdkVer"`
		Event   string `json:"Event"`
		Content struct {
			RobotWxid     string `json:"robot_wxid"`
			Type          int    `json:"type"`
			FromGroup     string `json:"from_group"`
			FromGroupName string `json:"from_group_name"`
			FromWxid      string `json:"from_wxid"`
			FromName      string `json:"from_name"`
			Msg           string `json:"msg"`
			// MsgSource     struct {
			// 	Atuserlist []struct {
			// 		Wxid         string `json:"wxid"`
			// 		Nickname     string `json:"nickname"`
			// 		PositionFrom int    `json:"position_from"`
			// 		PositionTo   int    `json:"position_to"`
			// 	} `json:"atuserlist"`
			// } `json:"msg_source"`
			Clientid  int `json:"clientid"`
			RobotType int `json:"robot_type"`
		} `json:"content"`
		// WsMCBreqID int `json:"wsMCBreqID"`
	}
	ag := &AutoGenerated{}
	err := json.Unmarshal(data, ag)
	logs.Info(err)

	logs.Info("接收到信息" + ag.Event)
}
