package controllers

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"github.com/beego/beego/v2/core/logs"
	"github.com/cdle/xdd/models"
	"strings"
)

type WxController struct {
	BaseController
}

func (c *WxController) HandleMessage() {
	data := c.Ctx.Input.RequestBody

	type AutoGenerated struct {
		SdkVer  int    `json:"sdkVer"`
		Event   string `json:"Event"`
		Content struct {
			RobotWxid     string `json:"robot_wxid"`
			Type          int    `json:"type"`
			FromGroup     string `json:"from_group"`
			FromGroupName string `json:"from_group_name"`
			FromWxid      string `json:"from_wxid"`
			FromName      string `json:"from_name"`
			Msg           string `json:"msg"`
			Clientid      int    `json:"clientid"`
			RobotType     int    `json:"robot_type"`
		} `json:"content"`
	}

	ag := &AutoGenerated{}
	err := json.Unmarshal(data, ag)
	logs.Info(err)
	logs.Info(string(data))
	logs.Info("接收到信息" + ag.Content.Msg)
	models.ListenWXTempPrivateMessage(ag.Content.FromWxid, ag.Content.Msg)

}

func u2s(form string) (to string, err error) {
	bs, err := hex.DecodeString(strings.Replace(form, `\u`, ``, -1))
	if err != nil {
		return
	}
	for i, bl, br, r := 0, len(bs), bytes.NewReader(bs), uint16(0); i < bl; i += 2 {
		binary.Read(br, binary.BigEndian, &r)
		to += string(r)
	}
	return
}
