package models

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"regexp"
	"strings"
	"time"

	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"github.com/buger/jsonparser"
)

//mode:  #模式 balance(均衡模式)、parallel(平行模式) 我一般留空
//containers:  #容器，可配置多个
//#############################################################
//  - address: http://192.168.31.47:5700 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
//#    username: admin #用户名，2.9以上不需要
//#    password: admin #密码
//    cid: jOABCDDDD-G2 #Client ID 青龙2.9开启二级验证后复制过来
//    secret: dsdfsdfsdfsdfsf #Client Secret 青龙2.9开启二级验证后复制过来
//    weigth: 3 #权重 balance模式下权重越高分得的ck越多，默认1
//    mode: balance #单独对容器进行模式设置
//    limit:  #限制容器ck数目
//    resident: jd_xxx&jd_cccc
//#############################################################
//  - address: http://192.168.31.48:5700 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
//#    username: admin #用户名，2.9以上不需要
//#    password: admin #密码
//    cid: jOABCDDDD-G2 #Client ID 青龙2.9开启二级验证后复制过来
//    secret: dsdfsdfsdfsdfsf #Client Secret 青龙2.9开启二级验证后复制过来
//    weigth: 3 #权重 balance模式下权重越高分得的ck越多，默认1
//    mode: balance #单独对容器进行模式设置
//    limit:  #限制容器ck数目
//    resident: jd_aaa&jd_bbb
//#############################################################
//  - address: http://192.168.31.49:5701 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
//#    username: admin #用户名，2.9以上不需要
//#    password: admin #密码
//    cid: jOABCDDDD-G2 #Client ID 青龙2.9开启二级验证后复制过来
//    secret: dsdfsdfsdfsdfsf #Client Secret 青龙2.9开启二级验证后复制过来
//    weigth: 3 #权重 balance模式下权重越高分得的ck越多，默认1
//    mode: parallel #单独对容器进行模式设置,平行模式专跑88,锦鲤.开卡之类
//    resident: jd_ddd&jd_eee
//#############################################################

type Token struct {
	Expiration time.Time
	Token      string
	Address    string
}

type Container struct {
	Type      string
	Name      string
	Address   string
	Cid       string
	Secret    string
	Version   string
	Token     string
	Available bool
	Delete    []string
	Weigth    int
	Mode      string
	Config    string
	Limit     int
	cks       []JdCookie
	Resident  string
	Task
}

func initContainer() {
	var ql = 0
	for i := range Config.Containers {
		if Config.Containers[i].Weigth == 0 {
			Config.Containers[i].Weigth = 1
		}
		Config.Containers[i].Type = ""
		if Config.Containers[i].Address != "" {
			vv := regexp.MustCompile(`^(https?://[\.\w]+:?\d*)`).FindStringSubmatch(Config.Containers[i].Address)
			if len(vv) == 2 {
				Config.Containers[i].Address = vv[1]
			} else {
				logs.Warn("%s地址错误", Config.Containers[i].Type)
			}
			err := Config.Containers[i].getToken()
			if err == nil {
				logs.Info("青龙" + version + "通道登录成功")
				ql++
				Config.Containers[i].Type = "ql"
				Config.Containers[i].Version = "openapi"
			}
		}
	}

	//(&JdCookie{}).Push(fmt.Sprintf("容器加载完毕，共%d个", ql))
}

func (c *Container) write(cks []JdCookie) error {
	switch c.Type {
	case "ql":
		if len(c.Delete) > 0 {
			c.request("/api/envs", DELETE, fmt.Sprintf(`[%s]`, strings.Join(c.Delete, ",")))
		}
		var hh []string
		if len(cks) != 0 {
			for _, ck := range cks {
				if ck.Available == True {
					if Config.Note == "pin" {
						hh = append(hh, fmt.Sprintf(`{"name":"JD_COOKIE","value":"pt_key=%s;pt_pin=%s;","remarks":"%s"}`, ck.PtKey, ck.PtPin, ck.Nickname))
					} else {
						hh = append(hh, fmt.Sprintf(`{"name":"JD_COOKIE","value":"pt_key=%s;pt_pin=%s;","remarks":"%s"}`, ck.PtKey, ck.PtPin, ck.Note))
					}
				}
			}
			c.request("/api/envs", POST, fmt.Sprintf(`[%s]`, strings.Join(hh, ",")))
			if Config.IsHelp {
				type AutoGenerated struct {
					Code int `json:"code"`
					Data []struct {
						Value     string  `json:"value"`
						ID        string  `json:"_id"`
						IntID     int     `json:"id"`
						Created   int64   `json:"created"`
						Status    int     `json:"status"`
						Timestamp string  `json:"timestamp"`
						Position  float64 `json:"position"`
						Name      string  `json:"name"`
						Remarks   string  `json:"remarks,omitempty"`
					} `json:"data"`
				}
				//help := getQLHelp(len(cks))
				//for k := range help {
				//	var data, err = c.request("/api/envs?searchValue=" + k)
				//	a := AutoGenerated{}
				//	err = json.Unmarshal(data, &a)
				//	if err != nil {
				//		continue
				//	}
				//	var toDelete []string
				//	for _, env := range a.Data {
				//		if env.IntID == 0 {
				//			toDelete = append(toDelete, fmt.Sprintf("\"%s\"", env.ID))
				//		} else {
				//			toDelete = append(toDelete, fmt.Sprintf("\"%d\"", env.IntID))
				//		}
				//		//toDelete = append(toDelete, fmt.Sprintf("\"%s\"", env.ID))
				//	}
				//	logs.Info(toDelete)
				//	if len(toDelete) > 0 {
				//		c.request("/api/envs", DELETE, fmt.Sprintf(`[%s]`, strings.Join(toDelete, ",")))
				//	}
				//}
				//for k, v := range help {
				//	if v == "" {
				//		v = "&"
				//	}
				//	r := map[string]string{
				//		"name":  k,
				//		"value": v,
				//	}
				//	d, _ := json.Marshal(r)
				//	c.request("/api/envs", POST, fmt.Sprintf(`[%s]`, string(d)))
				//}
			}
		}
	}
	return nil
}

func (c *Container) read() error {
	c.Available = true
	switch c.Type {
	case "ql":
		type AutoGenerated struct {
			Code int `json:"code"`
			Data []struct {
				Value     string  `json:"value"`
				ID        string  `json:"_id"`
				IntID     int     `json:"id"`
				Created   int64   `json:"created"`
				Status    int     `json:"status"`
				Timestamp string  `json:"timestamp"`
				Position  float64 `json:"position"`
				Name      string  `json:"name"`
				Remarks   string  `json:"remarks,omitempty"`
			} `json:"data"`
		}
		var data, err = c.request("/api/envs?searchValue=JD_COOKIE")
		a := AutoGenerated{}
		err = json.Unmarshal(data, &a)
		if err != nil {
			c.Available = false
			return err
		}
		c.Delete = []string{}

		for _, env := range a.Data {
			if env.IntID == 0 {
				c.Delete = append(c.Delete, fmt.Sprintf("\"%s\"", env.ID))
			} else {
				c.Delete = append(c.Delete, fmt.Sprintf("\"%d\"", env.IntID))
			}
			//c.Delete = append(c.Delete, fmt.Sprintf("\"%s\"", env.ID))
			res := regexp.MustCompile(`pt_key=(\S+);pt_pin=([^\s;]+);?`).FindAllStringSubmatch(env.Value, -1)
			for _, v := range res {
				CheckIn(v[2], v[1])
			}
		}
		return nil
	}
	return nil
}

func (c *Container) getToken() error {
	token := &Token{}
	req := httplib.Get(c.Address + fmt.Sprintf(`/open/auth/token?client_id=%s&client_secret=%s`, c.Cid, c.Secret))
	req.Header("Content-Type", "application/json;charset=UTF-8")
	if rsp, err := req.Response(); err == nil {
		data, err := ioutil.ReadAll(rsp.Body)
		if err != nil {
			return err
		}
		c.Token, _ = jsonparser.GetString(data, "data", "token")
		token.Token, _ = jsonparser.GetString(data, "data", "token")
		zero, _ := time.ParseInLocation("2006-01-02", time.Now().Local().Format("2006-01-02"), time.Local)
		token.Expiration = zero
		token.Address = c.Address
		c.Token = token.Token
	} else {
		return err
	}
	return nil

}

func (c *Container) request(ss ...string) ([]byte, error) {
	var api, method, body string
	for _, s := range ss {
		if s == GET || s == POST || s == PUT || s == DELETE {
			method = s
		} else if strings.Contains(s, "/api/") {
			if c.Version == "openapi" {
				api = strings.ReplaceAll(s, "api", "open")
			} else {
				api = s
			}
		} else {
			body = s
		}
	}
	var req *httplib.BeegoHTTPRequest
	var i = 0
	for {
		i++
		switch method {
		case POST:
			req = httplib.Post(c.Address + api)
		case PUT:
			req = httplib.Put(c.Address + api)
		case DELETE:
			req = httplib.Delete(c.Address + api)
		default:
			req = httplib.Get(c.Address + api)
		}
		req.Header("Authorization", "Bearer "+c.Token)
		if body != "" {
			req.Header("Content-Type", "application/json;charset=UTF-8")
			req.Body(body)
		}
		if data, err := req.Bytes(); err == nil {
			code, _ := jsonparser.GetInt(data, "code")
			if code == 200 {
				return data, nil
			} else {
				logs.Warn(string(data))
				logs.Info(c.Address + "错误")
				if i >= 5 {
					return nil, errors.New("异常")
				}
				c.getToken()
			}
		}
	}
	return []byte{}, nil
}

const (
	GET    = "GET"
	POST   = "POST"
	PUT    = "PUT"
	DELETE = "DELETE"
)
