package models

import (
	"encoding/json"
	"fmt"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"github.com/buger/jsonparser"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

var msgchan = make(chan []byte)

func init() {
	killp()
	for _, arg := range os.Args {
		if arg == "-d" {
			Daemon()
		}
	}
	ExecPath, _ = filepath.Abs(filepath.Dir(os.Args[0]))
	logs.Info("当前%s", ExecPath)
	go WriteMsg(msgchan)
	initConfig()
	initDB()
	initSysConfig()
	go initVersion()
	initContainer()
	initCron()
	go initTgBot()
	InitReplies()
	initTask()
	initNolan()
	//go initOrder(branchHelpOrderQueue, "jd_qmckd_branchHelp", "jd_qmckd_inviteIdArr_expand")
	//initRepos()
	initWX()
	tempToken()
}

func initNolan() {

	s, _ := httplib.Get(fmt.Sprintf("http://auth.smxy.xyz/user/auth3?qqNum=%s&version=%s", strconv.Itoa(Config.QQID), Config.Version)).String()
	contains := strings.Contains(s, "true")
	logs.Info(s)
	if contains {
		Config.VIP = true
		logs.Info("VIP验证成功")
	} else {
		logs.Info("VIP校验失败")
	}
}

func initWX() {
	env := GetEnv("WxGroupID")
	Config.WXGroupID = env
}

func getFriends() {
	type AutoGenerated struct {
		ISRefersh int    `json:"is_refresh"`
		Token     string `json:"token"`
		RobotWxid string `json:"robot_wxid"`
		API       string `json:"api"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated{
		Token:     Config.Wx.Token,
		API:       "GetFriendlist",
		RobotWxid: Config.Wx.Robotid,
		ISRefersh: 0,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.Bytes()
	list, _, _, _ := jsonparser.Get(s, "ReturnJson")
	jsonparser.ArrayEach(list, func(value []byte, dataType jsonparser.ValueType, offset int, err error) {
		var wxUser WxUser
		json.Unmarshal(value, &wxUser)
		db.Create(&wxUser)
	})
}
