package models

import (
	"encoding/json"
	"fmt"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"os"
	"time"
)

var msgchan = make(chan []byte)

func InitChan() {
	go WriteMsg(msgchan)
}

type QQMessage struct {
	Action string `json:"action"`
	QQMsg  struct {
		MessageType string `json:"message_type"`
		UserId      int    `json:"user_id"`
		GroupID     int    `json:"group_id"`
		Message     string `json:"message"`
	} `json:"params"`
	Echo      string `json:"echo"`
	MessageId int    `json:"message_id"`
}

func SendWxImg(uid string, file []byte) {

	unix := time.Now().Unix()

	filename := ExecPath + fmt.Sprintf("/%d.jpg", unix)

	f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		logs.Warn("zqdyj.txt失败，", err)
	}
	f.Write(file)
	f.Close()

	img := uploadImg(filename)

	os.Remove(filename)

	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Path      string `json:"path"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendImageMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Path:      img,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)
}

func SendWxMsg(uid string, msg string) {

	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Msg       string `json:"msg"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendTextMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Msg:       msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}

func SendWxGroupMsg(uid string, gid string, msg string) {

	type AutoGenerated1 struct {
		MemberWxid string `json:"member_wxid"`
		MemberName string `json:"member_name"`
		Msg        string `json:"msg"`
		Token      string `json:"token"`
		RobotWxid  string `json:"robot_wxid"`
		GroupWxid  string `json:"group_wxid"`
		API        string `json:"api"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:      Config.Wx.Token,
		API:        "SendGroupMsgAndAt",
		RobotWxid:  Config.Wx.Robotid,
		MemberWxid: uid,
		GroupWxid:  gid,
		Msg:        msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}

func SendQQMsg(msg QQMessage) {
	marshal, _ := json.Marshal(msg)
	logs.Info(string(marshal))
	msgchan <- marshal

}

func DeleteQQMsg(msgid int) {
	marshal, _ := json.Marshal(struct {
		Action string `json:"action"`
		QQMsg  struct {
			MessageId int `json:"message_id"`
		} `json:"params"`
	}{
		Action: "delete_msg",
		QQMsg: struct {
			MessageId int `json:"message_id"`
		}{
			MessageId: msgid,
		},
	})
	logs.Info(string(marshal))
	msgchan <- marshal
}

func AutoAgreeFriedns(flag string) {
	marshal, _ := json.Marshal(struct {
		Action string `json:"action"`
		QQMsg  struct {
			Approve string `json:"approve"`
			Remark  string `json:"remark"`
			Flag    string `json:"flag"`
		} `json:"params"`
	}{
		Action: "set_friend_add_request",
		QQMsg: struct {
			Approve string `json:"approve"`
			Remark  string `json:"remark"`
			Flag    string `json:"flag"`
		}{
			Approve: "true",
			Remark:  "",
			Flag:    flag,
		},
	})
	logs.Info(string(marshal))
	msgchan <- marshal
}
