package models

import (
	"encoding/json"
	"fmt"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"os"
	"strings"
	"time"
)

type QQMessage struct {
	UserId  int
	GroupId int
	Message string
}

func SendWxImg(uid string, file []byte) {
	type QXMessage struct {
		Type string `json:"type"`
		Data struct {
			Wxid string `json:"wxid"`
			Path string `json:"path"`
		} `json:"data"`
	}
	unix := time.Now().Unix()

	filename := ExecPath + fmt.Sprintf("/static/%d.jpg", unix)

	f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		logs.Warn("zqdyj.txt失败，", err)
	}
	f.Write(file)
	f.Close()

	img := uploadImg(filename)

	os.Remove(filename)

	req := httplib.Post(Config.Wx.Url + "DaenWxHook/httpapi/?wxid=" + Config.Wx.Robotid)
	reply := &QXMessage{
		Type: "Q0010",
		Data: struct {
			Wxid string `json:"wxid"`
			Path string `json:"path"`
		}{
			Wxid: uid,
			Path: img,
		},
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}

func SendWxMsg(uid string, msg string) {
	msg = strings.ReplaceAll(msg, "\n", "\r")
	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Msg       string `json:"msg"`
	}

	type QXMessage struct {
		Type string `json:"type"`
		Data struct {
			Wxid string `json:"wxid"`
			Msg  string `json:"msg"`
		} `json:"data"`
	}

	logs.Info(Config.Wx.Url + "/DaenWxHook/httpapi/?wxid=" + Config.Wx.Robotid)
	logs.Info(Config.Wx.Robotid)

	req := httplib.Post(Config.Wx.Url + "DaenWxHook/httpapi/?wxid=" + Config.Wx.Robotid)
	reply := &QXMessage{
		Type: "Q0001",
		Data: struct {
			Wxid string `json:"wxid"`
			Msg  string `json:"msg"`
		}{
			Wxid: uid,
			Msg:  msg,
		},
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

	//req := httplib.Post(Config.Wx.Url)
	//reply := &AutoGenerated1{
	//	Token:     "1",
	//	API:       "SendTextMsg",
	//	RobotWxid: Config.Wx.Robotid,
	//	ToWxid:    uid,
	//	Msg:       msg,
	//}
	//random := browser.Random()
	//req.Header("User-Agent", random)
	//marshal, _ := json.Marshal(reply)
	//logs.Info(string(marshal))
	//req.Body(string(marshal))
	//s, _ := req.String()
	//logs.Info(s)
}

func SendQQMsg(msg QQMessage) {
	value := GetEnv("qqurl")
	if value == "" {
		logs.Info("QQ服务未开启")
		return
	} else {
		post := httplib.Post(value + "/send_msg")
		logs.Info(value + "/send_msg")
		post.Header("Content-Type", "application/json")
		marshal, _ := json.Marshal(msg)
		logs.Info(string(marshal))
		post.Body(string(marshal))
		s, _ := post.String()
		logs.Info(s)
	}
}
