package models

import (
	"encoding/json"
	"fmt"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/buger/jsonparser"
	"os"
	"time"
	"strings"
"strconv"

)

var msgchan = make(chan []byte)

func InitChan() {
	go WriteMsg(msgchan)
}

// qxBaseURL 千寻 HTTP 根地址（去掉尾部斜杠）
func qxBaseURL() string {
	return strings.TrimRight(strings.TrimSpace(Config.Wx.Url), "/")
}

func qxHttpAPIURL() string {
	return fmt.Sprintf("%s/DaenWxHook/httpapi/?wxid=%s", qxBaseURL(), Config.Wx.Robotid)
}

func qxPostHook(body interface{}) (string, error) {
	url := qxHttpAPIURL()
	raw, err := json.Marshal(body)
	if err != nil {
		return "", err
	}
	req := httplib.Post(url)
	req.Header("Content-Type", "application/json")
	req.Header("User-Agent", browser.Random())
	req.Body(string(raw))
	Bot().Infof("[qx] POST %s body=%s", url, string(raw))
	resp, err := req.String()
	if err != nil {
		Bot().Errorf("[qx] 请求失败: %v", err)
		return "", err
	}
	Bot().Infof("[qx] resp=%s", resp)
	return resp, nil
}

// QxPostHook 供 controllers 调用千寻 DaenWxHook
func QxPostHook(body interface{}) (string, error) {
	return qxPostHook(body)
}

type QQMessage struct {
	Action string `json:"action"`
	QQMsg  struct {
		MessageType string `json:"message_type"`
		UserId      int    `json:"user_id"`
		GroupID     int    `json:"group_id"`
		Message     string `json:"message"`
	} `json:"params"`
	Echo      string `json:"echo"`
	MessageId int    `json:"message_id"`
}

func SendWxImg(uid string, file []byte) {

	unix := time.Now().Unix()

	filename := ExecPath + fmt.Sprintf("/%d.jpg", unix)

	f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		Bot().Warnf("zqdyj.txt失败，", err)
	}
	f.Write(file)
	f.Close()

	img := uploadImg(filename)

	os.Remove(filename)

	switch Config.Wx.Model {
	case "qx":
		type QXMessage struct {
			Type string `json:"type"`
			Data struct {
				Wxid string `json:"wxid"`
				Path string `json:"path"`
			} `json:"data"`
		}
		reply := &QXMessage{
			Type: "Q0010",
			Data: struct {
				Wxid string `json:"wxid"`
				Path string `json:"path"`
			}{
				Wxid: uid,
				Path: img,
			},
		}
		_, _ = qxPostHook(reply)
	case "my":
		type AutoGenerated1 struct {
			Token     string `json:"token"`
			API       string `json:"api"`
			RobotWxid string `json:"robot_wxid"`
			ToWxid    string `json:"to_wxid"`
			Path      string `json:"path"`
		}

		req := httplib.Post(Config.Wx.Url)
		reply := &AutoGenerated1{
			Token:     Config.Wx.Token,
			API:       "SendImageMsg",
			RobotWxid: Config.Wx.Robotid,
			ToWxid:    uid,
			Path:      img,
		}
		random := browser.Random()
		req.Header("User-Agent", random)
		marshal, _ := json.Marshal(reply)
		Bot().Infof(string(marshal))
		req.Body(string(marshal))
		s, _ := req.String()
		Bot().Infof(s)
	case "wechat08":
		Wechat08SendImgURL(uid, img)
	default:
		Bot().Infof("尚未配置微信")
	}

}

func SendWxMsg(uid string, msg string) {

	switch Config.Wx.Model {
	case "qx":
		msg = strings.ReplaceAll(msg, "\n", "\r")
		type QXMessage struct {
			Type string `json:"type"`
			Data struct {
				Wxid string `json:"wxid"`
				Msg  string `json:"msg"`
			} `json:"data"`
		}

		reply := &QXMessage{
			Type: "Q0001",
			Data: struct {
				Wxid string `json:"wxid"`
				Msg  string `json:"msg"`
			}{
				Wxid: uid,
				Msg:  msg,
			},
		}
		_, _ = qxPostHook(reply)
	case "my":
		type AutoGenerated1 struct {
			Token     string `json:"token"`
			API       string `json:"api"`
			RobotWxid string `json:"robot_wxid"`
			ToWxid    string `json:"to_wxid"`
			Msg       string `json:"msg"`
		}

		req := httplib.Post(Config.Wx.Url)
		reply := &AutoGenerated1{
			Token:     Config.Wx.Token,
			API:       "SendTextMsg",
			RobotWxid: Config.Wx.Robotid,
			ToWxid:    uid,
			Msg:       msg,
		}
		random := browser.Random()
		req.Header("User-Agent", random)
		marshal, _ := json.Marshal(reply)
		Bot().Infof(string(marshal))
		req.Body(string(marshal))
		s, _ := req.String()
		Bot().Infof(s)
	case "inner":

	case "wechat08":
		Wechat08SendMsg(uid, msg)
	default:
		Bot().Infof("尚未配置")
	}

}

func GetWxNickname(wxid string) string {
	type AutoGenerated struct {
		Token     string `json:"token"`
		API       int    `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		Wxid      string `json:"wxid"`
	}
	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated{
		Token:     Config.Wx.Token,
		API:       11,
		RobotWxid: Config.Wx.Robotid,
		Wxid:      wxid,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	req.Body(string(marshal))
	response, err := req.String()
	if err != nil {
		Error("获取昵称失败:", err)
		return ""
	}
	nickname, _ := jsonparser.GetString([]byte(response), "nickname")
	return nickname
}

func SendWxGroupMsg(uid string, gid string, msg string) {

	switch Config.Wx.Model {
	case "my":
		type AutoGenerated1 struct {
			MemberWxid string `json:"member_wxid"`
			MemberName string `json:"member_name"`
			Msg        string `json:"msg"`
			Token      string `json:"token"`
			RobotWxid  string `json:"robot_wxid"`
			GroupWxid  string `json:"group_wxid"`
			API        string `json:"api"`
		}

		req := httplib.Post(Config.Wx.Url)
		reply := &AutoGenerated1{
			Token:      Config.Wx.Token,
			API:        "SendGroupMsgAndAt",
			RobotWxid:  Config.Wx.Robotid,
			MemberWxid: uid,
			GroupWxid:  gid,
			Msg:        msg,
		}
		random := browser.Random()
		req.Header("User-Agent", random)
		marshal, _ := json.Marshal(reply)
		Bot().Infof(string(marshal))
		req.Body(string(marshal))
		s, _ := req.String()
		Bot().Infof(s)
	case "qx":
		msg = strings.ReplaceAll(msg, "\n", "\r")
		_, _ = qxPostHook(map[string]interface{}{
			"type": "Q0001",
			"data": map[string]string{
				"wxid": gid,
				"msg":  msg,
			},
		})
	case "wechat08":
		Wechat08SendGroupAt(uid, gid, msg)
	default:
		Bot().Infof("尚未配置")
	}

}


func SendWxImg2(uid string, msg string) {
	switch Config.Wx.Model {
	case "my":	
	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Path      string `json:"path"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendImageMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Path:      msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	Bot().Infof(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	Bot().Infof(s)

	case "qx":
		requestBody := map[string]interface{}{
			"type": "Q0010",
			"data": map[string]string{
				"wxid": uid,
				"path": msg,
			},
		}
		_, _ = qxPostHook(requestBody)

	case "wechat08":
		Wechat08SendImgURL(uid, msg)
	default:
		Bot().Infof("尚未配置发送模式")
	}
}

func TransferRequest(toWxid string, transferid string, money string) error {
	// 构造请求 URL
	url := qxHttpAPIURL()

	// 构造请求数据
	requestBody := map[string]interface{}{
		"type": "Q0016",
		"data": map[string]string{
			"wxid":       toWxid,
			"transferid": transferid,
		},
	}
	payload, err := json.Marshal(requestBody)
	if err != nil {
		Error("构造请求体失败:", err)
		return err
	}

	// 发起 POST 请求
	req := httplib.Post(url)
	req.Header("Content-Type", "application/json") // 设置请求头
	req.Body(payload)                             // 设置请求体

	// 发送请求并获取响应
	resp, err := req.String()
	if err != nil {
		Error("HTTP 请求失败:", err)
		return err
	}

	// 打印响应结果
	Bot().Infof("转账确认请求成功，响应结果:", resp)

	// 解析响应
	var response struct {
		State     bool   `json:"state"`
		Error     string `json:"error"`
		Timestamp string `json:"timestamp"`
	}

	err = json.Unmarshal([]byte(resp), &response)
	if err != nil {
		Error("解析响应失败:", err)
		return err
	}

	// 检查响应状态
	if !response.State {
		Error("转账失败，原因:", response.Error)
		return fmt.Errorf("转账失败: %s", response.Error)
	}

	return nil
}



func SendWxGroupMsg2(gid string, msg string) {
	if Config.Wx.Model == "wechat08" {
		Wechat08SendGroupMsg(gid, msg)
		return
	}
	if Config.Wx.Model == "qx" {
		msg = strings.ReplaceAll(msg, "\n", "\r")
		_, _ = qxPostHook(map[string]interface{}{
			"type": "Q0001",
			"data": map[string]string{
				"wxid": gid,
				"msg":  msg,
			},
		})
		return
	}

	type AutoGenerated1 struct {
//		MemberWxid string `json:"member_wxid"`
//		MemberName string `json:"member_name"`
		Msg        string `json:"msg"`
		Token      string `json:"token"`
		RobotWxid  string `json:"robot_wxid"`
		GroupWxid  string `json:"group_wxid"`
		API        string `json:"api"`
	}
	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:      Config.Wx.Token,
		API:        "SendGroupMsgAndAt",
		RobotWxid:  Config.Wx.Robotid,
		GroupWxid:  gid,
		Msg:        msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	Bot().Infof(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	Bot().Infof(s)

}


func SendQQMsg(msg QQMessage) {
	// 自动补全message_type：为空时根据GroupID/UserId判断
	if msg.QQMsg.MessageType == "" {
		if msg.QQMsg.GroupID > 0 {
			msg.QQMsg.MessageType = "group"
		} else if msg.QQMsg.UserId > 0 {
			msg.QQMsg.MessageType = "private"
		} else {
			Error("SendQQMsg: 无法确定消息类型，group_id和user_id均为空")
			return
		}
	}

	marshal, err := json.Marshal(msg)
	if err != nil {
		Error("序列化QQ消息失败：", err)
		return
	}
	Bot().Infof(string(marshal))
	msgchan <- marshal
}




func DeleteQQMsg(msgid int) {
	marshal, _ := json.Marshal(struct {
		Action string `json:"action"`
		QQMsg  struct {
			MessageId int `json:"message_id"`
		} `json:"params"`
	}{
		Action: "delete_msg",
		QQMsg: struct {
			MessageId int `json:"message_id"`
		}{
			MessageId: msgid,
		},
	})
	Bot().Infof(string(marshal))
	msgchan <- marshal
}

func AutoAgreeFriedns(flag string) {
	marshal, _ := json.Marshal(struct {
		Action string `json:"action"`
		QQMsg  struct {
			Approve string `json:"approve"`
			Remark  string `json:"remark"`
			Flag    string `json:"flag"`
		} `json:"params"`
	}{
		Action: "set_friend_add_request",
		QQMsg: struct {
			Approve string `json:"approve"`
			Remark  string `json:"remark"`
			Flag    string `json:"flag"`
		}{
			Approve: "true",
			Remark:  "",
			Flag:    flag,
		},
	})
	Bot().Infof(string(marshal))
	msgchan <- marshal
}



// 获取群成员信息的函数
func GetGroupMembers(groupID string) {
    marshal, _ := json.Marshal(struct {
        Action string `json:"action"`
        QQMsg  struct {
            GroupID string `json:"group_id"`
        } `json:"params"`
        Echo string `json:"echo"`
    }{
        Action: "get_group_member_list",
        QQMsg: struct {
            GroupID string `json:"group_id"`
        }{
            GroupID: groupID,
        },
        Echo: "get_group_member_list",
    })
    fmt.Println(string(marshal))
    msgchan <- marshal

    // 异步处理成员数据，防止阻塞
    go func() {
    }()
}

// 踢人
func RemoveGroupMember(groupID int, userID int64) {
    // 将int64类型的userID转换为int类型
    userIDInt := int(userID)
    SendQQGroup(groupID, userIDInt, "没有提交京东账号，确认为潜伏者，10分钟后将会被踢出群聊。。。。")

    // 异步处理踢人，避免阻塞主流程
    go func() {
        time.Sleep(time.Second * 60 * 10)
        marshal, _ := json.Marshal(struct {
            Action string `json:"action"`
            QQMsg  struct {
                GroupID int   `json:"group_id"`
                UserID  int64 `json:"user_id"`
            } `json:"params"`
        }{
            Action: "set_group_kick",
            QQMsg: struct {
                GroupID int   `json:"group_id"`
                UserID  int64 `json:"user_id"`
            }{
                GroupID: groupID,
                UserID:  userID,
            },
        })
        fmt.Println(string(marshal))
        msgchan <- marshal
    }()
}


// 获取用户QQ昵称（关键修改2：同步返回昵称）
func GetQQNickname(userID string) string {
    // 创建用于接收响应的通道
    replyChan := make(chan []byte, 1)
    // 构造请求体
    reqData := struct {
        Action string `json:"action"`
        Params struct {
            UserID string `json:"user_id"`
        } `json:"params"`
        Echo string `json:"echo"`
    }{
        Action: "get_stranger_info",
        Params: struct {
            UserID string `json:"user_id"`
        }{UserID: userID},
        Echo: "get_nickname_" + userID, // 用userID区分不同请求的响应
    }
    // 序列化请求
    marshal, err := json.Marshal(reqData)
    if err != nil {
        return "昵称获取失败（请求序列化错误）"
    }
    // 发送请求
    msgchan <- marshal

    // 等待响应（超时5秒）
    var resp []byte
    select {
    case resp = <-replyChan: // 假设响应会通过replyChan返回（需配合消息框架的响应分发）
    case <-time.After(5 * time.Second):
        return "昵称获取超时"
    }

    // 解析响应
    var result struct {
        Data struct {
            Nickname string `json:"nickname"` // 提取昵称
        } `json:"data"`
        Retcode int `json:"retcode"` // 状态码（0为成功）
    }
    if err := json.Unmarshal(resp, &result); err != nil {
        return "昵称解析失败"
    }
    if result.Retcode != 0 {
        return "获取失败（错误码：" + strconv.Itoa(result.Retcode) + "）"
    }
    return result.Data.Nickname // 返回解析到的昵称
}
