package models

import (
	"encoding/json"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"github.com/eatmoreapple/openwechat"
	"strings"
)

var friedns openwechat.Friends

var ListenUOSWXPrivateMessage = func(msg *openwechat.Message) {
	rt := handleMessage(msg.RawContent, "wx", msg.FromUserName)
	msg.ReplyText(rt.(string))
}

var ListenUOSWXGroupMessage = func(uid string, gid string, msg string) {
	if strings.Contains(Config.WXGroupID, gid) || msg == "监听微信群" || msg == "取消监听" {
		rt := handleMessage(msg, "wxg", uid, gid)
		switch rt.(type) {
		case string:
			SendWxGroupMsg(uid, gid, rt.(string))
		}
	}
}

func SendUosWxMsg(uid string, msg string) {

	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Msg       string `json:"msg"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendTextMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Msg:       msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}
