package models

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"github.com/buger/jsonparser"
	"github.com/robfig/cron/v3"
	"math/rand"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

func intiSky() {
	c := cron.New(cron.WithSeconds()) //精确到秒

	spec := GetEnv("cron")
	if spec == "" {
		spec = "0 " + strconv.Itoa(rand.Intn(59)) + " 0 /8 * * ?" //cron表达式，每秒一次
	}

	if isOpenWskey() {
		c.AddFunc(spec, func() {
			fmt.Println("开始wskey转换")
			updateCookie()
		})

		c.Start()
	}

}

type AutoGenerated struct {
	ClientVersion string `json:"clientVersion"`
	Client        string `json:"client"`
	Sv            string `json:"sv"`
	St            string `json:"st"`
	UUID          string `json:"uuid"`
	Sign          string `json:"sign"`
	FunctionID    string `json:"functionId"`
}

func getKey(WSCK string) (string, error) {
	var ptKey = ""
	sign := GetEnv("sign")
	if sign == "" {
		ptKey, _ = GetZKToken(WSCK)
	} else {
		ptKey, _ = getTokenKey(WSCK)
	}
	time.Sleep(time.Duration(rand.Int63n(3)) * time.Second)
	return ptKey, nil
}

/*

下面是自定义接口
*/

func getSelfToken() string {
	sign := GetEnv("sign")
	req := httplib.Post(sign)
	req.Param("body", "{}")
	req.Param("functionId", "genToken")
	data, _ := req.Bytes()
	logs.Info(string(data))
	getString, _ := jsonparser.GetString(data, "data", "convertUrl")
	return getString
}

func getTokenKey(WSCK string) (string, error) {
	s := getSelfToken()
	logs.Info(s)
	str := `https://api.m.jd.com/client.action?` + s + "&functionId=genToken"
	req := httplib.Post(str)
	req.Header("cookie", WSCK)
	req.Header("User-Agent", ua)
	req.Header("content-type", `application/x-www-form-urlencoded; charset=UTF-8`)
	req.Header("charset", `UTF-8`)
	req.Header("accept-encoding", `br,gzip,deflate`)
	req.Body(`%7B%22to%22%3A%20%22https%3A//m.jd.com%22%2C%20%22action%22%3A%20%22to%22%7D`)
	data, err := req.Bytes()
	if err != nil {
		return "", err
	}
	logs.Info(string(data))
	tokenKey, _ := jsonparser.GetString(data, "tokenKey")
	ptKey, _ := appjmp(tokenKey)
	return ptKey, nil
}

func appjmp(tokenKey string) (string, error) {

	v := url.Values{}
	v.Add("tokenKey", tokenKey)
	v.Add("to", `https://plogin.m.jd.com/jd-mlogin/static/html/appjmp_blank.html`)
	v.Add("client_type", "android")
	v.Add("appid", "879")
	v.Add("appup_type", "1")
	req := httplib.Get(`https://un.m.jd.com/cgi-bin/app/appjmp?` + v.Encode())
	req.Header("User-Agent", ua)
	req.Header("accept", `accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9`)
	req.Header("x-requested-with", "com.jingdong.app.mall")
	req.SetCheckRedirect(func(req *http.Request, via []*http.Request) error {
		return http.ErrUseLastResponse
	})
	rsp, err := req.Response()
	if err != nil {
		return "", err
	}
	cookies := strings.Join(rsp.Header.Values("Set-Cookie"), " ")
	//ptKey := FetchJdCookieValue("pt_key", cookies)
	//logs.Info(cookies)
	return cookies, nil
}

/*
Zy接口注释 一下全部走ZY接口
*/

func GetZKToken(wsKey string) (string, error) {
	url := checkCloud()
	return getZyToken(url, wsKey)
}

func checkCloud() string {
	urlList := []string{"aHR0cDovLzQzLjEzNS45MC4yMy8=", "aHR0cHM6Ly9zaGl6dWt1Lm1sLw==", "aHR0cHM6Ly9jZi5zaGl6dWt1Lm1sLw=="}
	for i := range urlList {
		decodeString, _ := base64.StdEncoding.DecodeString(urlList[i])
		req := httplib.Get(string(decodeString))
		req.Header("User-Agent", "python-requests/2.25.1")
		s, err := req.String()
		logs.Info(s, err)
		if strings.Contains(s, "200") && err == nil {
			return string(decodeString)
		}
	}
	decodeString, _ := base64.StdEncoding.DecodeString(urlList[0])
	return string(decodeString)
}

type T struct {
	Code      int    `json:"code"`
	Update    int    `json:"update"`
	Jdurl     string `json:"jdurl"`
	UserAgent string `json:"User-Agent"`
}
type T2 struct {
	FunctionId    string `json:"functionId"`
	ClientVersion string `json:"clientVersion"`
	Build         string `json:"build"`
	Client        string `json:"client"`
	Partner       string `json:"partner"`
	Oaid          string `json:"oaid"`
	SdkVersion    string `json:"sdkVersion"`
	Lang          string `json:"lang"`
	HarmonyOs     string `json:"harmonyOs"`
	NetworkType   string `json:"networkType"`
	Uemps         string `json:"uemps"`
	Ext           string `json:"ext"`
	Ef            string `json:"ef"`
	Ep            string `json:"ep"`
	St            int64  `json:"st"`
	Sign          string `json:"sign"`
	Sv            string `json:"sv"`
}

func cloudInfo(url string) string {
	// 重试10次
	for i := 0; i <= 10; i++ {
		req := httplib.Get(url + "check_api")
		req.Header("User-Agent", "python-requests/2.25.1")
		req.Header("authorization", "Bearer Shizuku")
		s, _ := req.Bytes()
		t := T{}
		json.Unmarshal(s, &t)
		logs.Info(t.UserAgent)
		if t.UserAgent != "" {
			return t.UserAgent
		}
		time.Sleep(time.Second * 2)
	}
	// 重试10次 还是失败 搞个默认值
	return "jdapp;android;10.3.5;;;appBuild/92468;ef/1;ep/{\"hdid\":\"JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw=\",\"ts\":1647918020020,\"ridx\":-1,\"cipher\":{\"sv\":\"CJS=\",\"ad\":\"EWOzY2ZuCNHsEWHvEJc3EG==\",\"od\":\"ENY0CJS3ZtvvCtK5ZJC5Yq==\",\"ov\":\"CzO=\",\"ud\":\"EWOzY2ZuCNHsEWHvEJc3EG==\"},\"ciphertype\":5,\"version\":\"1.2.0\",\"appname\":\"com.jingdong.app.mall\"};Mozilla/5.0 (Linux; Android 12; M2102K1C Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36"
}

func getZySign(urls string, ua string) T2 {
	t := T2{}
	for i := 0; i <= 10; i++ {
		req1 := httplib.Get(urls + "genToken")
		req1.Header("User-Agent", ua)
		s, _ := req1.Bytes()
		json.Unmarshal(s, &t)
		if t.Sign != "" {
			return t
		}
		time.Sleep(time.Second * 2)
	}
	bytes := []byte("{\"functionId\":\"genToken\",\"clientVersion\":\"10.3.5\",\"build\":\"92468\",\"client\":\"android\",\"partner\":\"google\",\"oaid\":\"06lr6e4tz0n0hjsq\",\"sdkVersion\":\"31\",\"lang\":\"zh_CN\",\"harmonyOs\":\"0\",\"networkType\":\"UNKNOWN\",\"uemps\":\"0-2\",\"ext\":\"{\\\"prstate\\\": \\\"0\\\", \\\"pvcStu\\\": \\\"1\\\"}\",\"ef\":\"1\",\"ep\":\"{\\\"hdid\\\":\\\"JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw=\\\",\\\"ts\\\":1647918629476,\\\"ridx\\\":-1,\\\"cipher\\\":{\\\"d_model\\\":\\\"JWunCVVidRTr\\\",\\\"wifiBssid\\\":\\\"dW5hbw93bq==\\\",\\\"osVersion\\\":\\\"CJS=\\\",\\\"d_brand\\\":\\\"WQvrb21f\\\",\\\"screen\\\":\\\"CJuyCMenCNq=\\\",\\\"uuid\\\":\\\"oXVmbQ1uD3P6azYzczLfbG==\\\",\\\"aid\\\":\\\"oXVmbQ1uD3P6azYzczLfbG==\\\",\\\"openudid\\\":\\\"oXVmbQ1uD3P6azYzczLfbG==\\\"},\\\"ciphertype\\\":5,\\\"version\\\":\\\"1.2.0\\\",\\\"appname\\\":\\\"com.jingdong.app.mall\\\"}\",\"st\":1647918629476,\"sign\":\"48869070986ea43e1b9dd6c4aad60ca7\",\"sv\":\"120\"}")
	json.Unmarshal(bytes, &t)
	return T2{}
}

func getZyToken(urls string, wskey string) (string, error) {
	ua := cloudInfo(urls)
	t := getZySign(urls, ua)
	v := url.Values{}
	v.Add("functionId", t.FunctionId)
	v.Add("clientVersion", t.ClientVersion)
	v.Add("build", t.Build)
	v.Add("client", t.Client)
	v.Add("partner", t.Partner)
	v.Add("oaid", t.Oaid)
	v.Add("sdkVersion", t.SdkVersion)
	v.Add("lang", t.Lang)
	v.Add("harmonyOs", t.HarmonyOs)
	v.Add("networkType", t.NetworkType)
	v.Add("uemps", t.Uemps)
	v.Add("ext", t.Ext)
	v.Add("ef", t.Ef)
	v.Add("ep", t.Ep)
	v.Add("st", strconv.FormatInt(t.St, 10))
	v.Add("sign", t.Sign)
	v.Add("sv", t.Sv)
	req := httplib.Post(`https://api.m.jd.com/client.action?` + v.Encode())
	req.Header("cookie", wskey)
	req.Header("User-Agent", ua)
	req.Header("content-type", `application/x-www-form-urlencoded; charset=UTF-8`)
	req.Header("charset", `UTF-8`)
	req.Header("accept-encoding", `br,gzip,deflate`)
	req.Body(`body=%7B%22to%22%3A%22https%253a%252f%252fplogin.m.jd.com%252fjd-mlogin%252fstatic%252fhtml%252fappjmp_blank.html%22%7D&`)
	data, err := req.Bytes()
	if err != nil {
		return "", err
	}
	tokenKey, _ := jsonparser.GetString(data, "tokenKey")
	cookie, err := appjmp(tokenKey)
	logs.Info(cookie)
	if err != nil {
		return "", err
	}
	return cookie, nil
}
