package models

import (
	"encoding/json"
	"fmt"
	browser "github.com/EDDYCJY/fake-useragent"
	"github.com/beego/beego/v2/client/httplib"
	"github.com/beego/beego/v2/core/logs"
	"os"
	"strings"
	"time"
)

var ListenWXTempPrivateMessage = func(uid string, msg string) {
	rt := handleMessage(msg, "wx", uid)
	switch rt.(type) {
	case string:
		SendWxMsg(uid, rt.(string))
	}
}

var ListenWXGroupMessage = func(uid string, gid string, msg string) {
	if strings.Contains(Config.WXGroupID, gid) || msg == "监听微信群" || msg == "取消监听" {
		rt := handleMessage(msg, "wxg", uid, gid)
		switch rt.(type) {
		case string:
			SendWxGroupMsg(uid, gid, rt.(string))
		}
	}

}

func SendWxMsg(uid string, msg string) {

	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Msg       string `json:"msg"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendTextMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Msg:       msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}

func SendWxGroupMsg(uid string, gid string, msg string) {

	type AutoGenerated1 struct {
		MemberWxid string `json:"member_wxid"`
		MemberName string `json:"member_name"`
		Msg        string `json:"msg"`
		Token      string `json:"token"`
		RobotWxid  string `json:"robot_wxid"`
		GroupWxid  string `json:"group_wxid"`
		API        string `json:"api"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:      Config.Wx.Token,
		API:        "SendGroupMsgAndAt",
		RobotWxid:  Config.Wx.Robotid,
		MemberWxid: uid,
		GroupWxid:  gid,
		Msg:        msg,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)

}

func SendWxImg(uid string, file []byte) {

	unix := time.Now().Unix()

	filename := ExecPath + fmt.Sprintf("/%d.jpg", unix)

	f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0777)
	if err != nil {
		logs.Warn("zqdyj.txt失败，", err)
	}
	f.Write(file)
	f.Close()

	img := uploadImg(filename)

	os.Remove(filename)

	type AutoGenerated1 struct {
		Token     string `json:"token"`
		API       string `json:"api"`
		RobotWxid string `json:"robot_wxid"`
		ToWxid    string `json:"to_wxid"`
		Path      string `json:"path"`
	}

	req := httplib.Post(Config.Wx.Url)
	reply := &AutoGenerated1{
		Token:     Config.Wx.Token,
		API:       "SendImageMsg",
		RobotWxid: Config.Wx.Robotid,
		ToWxid:    uid,
		Path:      img,
	}
	random := browser.Random()
	req.Header("User-Agent", random)
	marshal, _ := json.Marshal(reply)
	logs.Info(string(marshal))
	req.Body(string(marshal))
	s, _ := req.String()
	logs.Info(s)
}
